name = "graduation-site"
compatibility_date = "2024-09-23"
pages_build_output_dir = "out"

[[d1_databases]]
binding = "DB"
database_name = "graduation-db"
database_id = "4b224931-5e97-49ad-aee3-73a169382650"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "graduation-photos"
